# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The Dog Walker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The Dog Walker
pod ‘Firebase/Core’
pod ‘Firebase/Auth’
pod ‘Firebase/Database’


  target 'The Dog WalkerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'The Dog WalkerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
